PL/Controllers/DiscoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class DiscoController : Controller
    {
        // GET: Disco
        public ActionResult GetAll()
        {
            ML.Result resultado = BL.Disco.GetAll();
            ML.Disco disco = new ML.Disco();

            disco.Discos = resultado.Objects;

            return View(disco);
        }

        [HttpGet]
        public ActionResult Form(int? idDisco)
        {
            if (idDisco == null)
            {
                idDisco = 0;
            }

            if (idDisco == 0) // ADD
            {
                return View();
            }
            else // UPDATE
            {
                ML.Disco disco = new ML.Disco();
                ML.Result resultado = BL.Disco.GetById(idDisco.Value);

                disco = (ML.Disco)resultado.Object;

                return View(disco);
            }
        }
    }
}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Views/Disco/Form.cshtml
@model ML.Disco
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">Formulario</h2>
<hr />

<div>
    <div class="row">
        <div class="col">
            @Html.LabelFor(Model => Model.Titulo)
            @Html.TextBoxFor(Model => Model.Titulo, new { @class = "form-control" })
        </div>
        <div class="col">
            @Html.LabelFor(Model => Model.Artista)
            @Html.TextBoxFor(Model => Model.Artista, new { @class = "form-control" })
        </div>
    </div>

    <div class="row">
        <div class="col">
            @Html.LabelFor(Model => Model.GeneroMusical)
            @Html.TextBoxFor(Model => Model.GeneroMusical, new { @class = "form-control" })
        </div>
        <div class="col">
            @Html.LabelFor(Model => Model.Duracion)
            @Html.TextBoxFor(Model => Model.Duracion, new { @class = "form-control" })
        </div>
    </div>

    <div class="row">
        <div class="col">
            @Html.LabelFor(Model => Model.Anio)
            @Html.TextBoxFor(Model => Model.Anio, new { @class = "form-control" })
        </div>
        <div class="col">
            @Html.LabelFor(Model => Model.Distribuidora)
            @Html.TextBoxFor(Model => Model.Distribuidora, new { @class = "form-control" })
        </div>
    </div>

    <div class="row">
        <div class="col">
            @Html.LabelFor(Model => Model.Ventas)
            @Html.TextBoxFor(Model => Model.Ventas, new { @class = "form-control" })
        </div>

        
        <div class="col">
            @Html.LabelFor(Model => Model.Disponibilidad)
            @Html.TextBoxFor(Model => Model.Disponibilidad, new { @class = "form-control" })
        </div>
    </div>
    <br /> <hr />
    <center>
        <button class="btn btn-success">Registrar</button>
    </center>
</div>

PL/Views/Disco/GetAll.cshtml
@model ML.Disco
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">DISCOS</h2>
<br />
<h3 class="text-center">Agregar nuevo disco</h3>
<hr />

<center>
    <a class="btn btn-primary" href="@Url.Action("Form", "Disco")">Registrar nuevo disco</a>
</center>

<br />
<hr />

@if (Model.Discos.Count > 0)
{

    <h3 class="text-center">Discos registrados</h3>
    <hr />
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Titulo
                </th>
                <th>
                    Artista
                </th>
                <th>
                    Genero
                </th>
                <th>
                    Duracion
                </th>
                <th>
                    Año
                </th>
                <th>
                    Distribuidora
                </th>
                <th>
                    Ventas
                </th>
                <th>
                    Disponibilidad
                </th>
                <th>
                    Editar
                </th>
                <th>
                    Borrar
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (ML.Disco disco in Model.Discos)
            {
                <tr>
                    <td>
                        @disco.Id
                    </td>
                    <td>
                        @disco.Titulo
                    </td>
                    <td>
                        @disco.Artista
                    </td>
                    <td>
                        @disco.GeneroMusical
                    </td>
                    <td>
                        @disco.Duracion min
                    </td>
                    <td>
                        @disco.Anio.Year
                    </td>
                    <td>
                        @disco.Distribuidora
                    </td>
                    <td>
                        @disco.Ventas
                    </td>
                    <td>
                        @if (disco.Disponibilidad)
                        {
                            <p>Disponible</p>
                        }
                        else
                        {
                            <p>No disponible</p>
                        }
                    </td>
                    <td>
                        <a class="btn btn-primary" href="@Url.Action("Form", "Disco", new {idDisco = disco.Id})">Editar</a>
                    </td>
                    <td>
                        <button class="btn btn-danger">Borrar</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
}
else
{
    <div class="alert alert-danger">No se encontraron datos</div>
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/solid.css" integrity="sha384-Tv5i09RULyHKMwX0E8wJUqSOaXlyu3SQxORObAI08iUwIalMmN5L6AvlPX2LMoSE" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/fontawesome.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Disco", "GetAll", "Disco", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/solid.js" integrity="sha384-/BxOvRagtVDn9dJ+JGCtcofNXgQO/CCCVKdMfL115s3gOgQxWaX/tSq5V8dRgsbc" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/fontawesome.js" integrity="sha384-dPBGbj4Uoy1OOpM4+aRGfAOc0W37JkROT+3uynUgTHZCHZNMHfGXsmmvYTffZjYO" crossorigin="anonymous"></script>
</body>
</html>